import type { PerformanceInput } from "@/lib/types";

export type PerformanceFormFieldType = "time" | "number" | "text";

export type PerformanceFormFieldMeta = {
  key: keyof PerformanceInput;
  title: string;
  unit: string;
  placeholder?: string;
  type: PerformanceFormFieldType;
  /** Pour `type: "number"` — reps ≥0, kg >0, ou hauteur cm entière. */
  numberKind?: "reps" | "kg" | "cm";
};

/** Métadonnées des champs — même ordre que l’UI `/performances` (onglet Perf). */
export const PERFORMANCE_FORM_FIELDS: PerformanceFormFieldMeta[] = [
  {
    key: "row1k",
    title: "1 km rameur",
    unit: "mm:ss",
    placeholder: "03:32",
    type: "time",
  },
  {
    key: "skiErg500",
    title: "500 m SkiErg",
    unit: "mm:ss",
    placeholder: "01:52",
    type: "time",
  },
  {
    key: "run400m",
    title: "400 m piste",
    unit: "mm:ss",
    placeholder: "01:08",
    type: "time",
  },
  {
    key: "row2k",
    title: "2 km rameur",
    unit: "mm:ss",
    placeholder: "07:15",
    type: "time",
  },
  {
    key: "run5k",
    title: "5 km course",
    unit: "mm:ss",
    placeholder: "24:20",
    type: "time",
  },
  {
    key: "run10k",
    title: "10 km course",
    unit: "mm:ss",
    placeholder: "48:30",
    type: "time",
  },
  {
    key: "swim400m",
    title: "400 m piscine",
    unit: "mm:ss",
    placeholder: "06:45",
    type: "time",
  },
  {
    key: "run1kIncline",
    title: "1 km tapis incliné (2 %)",
    unit: "mm:ss",
    placeholder: "04:10",
    type: "time",
  },
  {
    key: "bikeErg1k",
    title: "1 km BikeErg",
    unit: "mm:ss",
    placeholder: "02:25",
    type: "time",
  },
  {
    key: "bikeErg2k",
    title: "2 km BikeErg",
    unit: "mm:ss",
    placeholder: "04:50",
    type: "time",
  },
  {
    key: "skiErg2k",
    title: "2 km SkiErg",
    unit: "mm:ss",
    placeholder: "09:30",
    type: "time",
  },
  {
    key: "echoBikeCal1min",
    title: "Echo / Assault Bike — calories (1 min)",
    unit: "cal",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "echoBike10cal",
    title: "Echo Bike — temps 10 calories",
    unit: "mm:ss",
    placeholder: "00:32",
    type: "time",
  },
  {
    key: "echoBike30cal",
    title: "Echo Bike — temps 30 calories",
    unit: "mm:ss",
    placeholder: "01:45",
    type: "time",
  },
  {
    key: "wallBall150",
    title: "Wall ball ×150",
    unit: "mm:ss",
    placeholder: "06:15",
    type: "time",
  },
  {
    key: "pullups",
    title: "Tractions strictes",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "dipsStrict",
    title: "Dips parallèles stricts (set max)",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "hspuStrict",
    title: "HSPU stricts (set max)",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "muscleUp2min",
    title: "Muscle-ups stricts (2 min)",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "toesToBar",
    title: "Toes-to-bar stricts",
    unit: "reps (set max)",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "burpees50",
    title: "50 burpees",
    unit: "mm:ss",
    placeholder: "08:45",
    type: "time",
  },
  {
    key: "airSquat100",
    title: "100 air squats",
    unit: "mm:ss",
    placeholder: "04:30",
    type: "time",
  },
  {
    key: "kbSwing100",
    title: "100 KB swings (american, poids protocole)",
    unit: "mm:ss",
    placeholder: "03:45",
    type: "time",
  },
  {
    key: "hybridDbChipper",
    title: "Chipper : thrusters DB + burpees + DU",
    unit: "mm:ss",
    placeholder: "12:00",
    type: "time",
  },
  {
    key: "doubleUnders1min",
    title: "Double-unders (1 min)",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "pushupsStrict",
    title: "Pompes strictes (set max)",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "ropeClimb2min",
    title: "Montées de corde strictes (2 min)",
    unit: "reps",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "lunges2min",
    title: "Fentes alternées sans charge (2 min)",
    unit: "pas (reps)",
    type: "number",
    numberKind: "reps",
  },
  {
    key: "frontSquat5",
    title: "Front squat ×5",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "backSquat3",
    title: "Back squat ×3",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "bulgarianSplitSquat8",
    title: "Bulgarian split squat ×8/jambe (somme 2 haltères, kg)",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "benchPress5",
    title: "Développé couché ×5 (barre)",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "ohp5",
    title: "Développé militaire strict ×5 (barre)",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "tbarRow10",
    title: "Rowing T-bar (machine) ×10",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "deadlift5",
    title: "Deadlift ×5",
    unit: "kg",
    type: "number",
    numberKind: "kg",
  },
  {
    key: "boxJumpMaxCm",
    title: "Box jump — hauteur max (cm)",
    unit: "cm",
    type: "number",
    numberKind: "cm",
  },
  {
    key: "farmerCarry",
    title: "Farmer carry",
    unit: "m / s",
    placeholder: "40/35",
    type: "text",
  },
  {
    key: "sandbagCarry",
    title: "Sandbag carry",
    unit: "m / s",
    placeholder: "40/50",
    type: "text",
  },
  {
    key: "sledCarry",
    title: "Sled 50 m (push ou pull)",
    unit: "m / s",
    placeholder: "50/55",
    type: "text",
  },
  {
    key: "hollowHold",
    title: "Hollow hold",
    unit: "mm:ss",
    placeholder: "01:20",
    type: "time",
  },
  {
    key: "lSitHold",
    title: "L-sit (parallèles)",
    unit: "mm:ss",
    placeholder: "00:25",
    type: "time",
  },
];
